language: r
sudo: false
cache: packages

env:
  _R_CHECK_FORCE_SUGGESTS_=false

r:
 - 3.1
 - 3.2
 - oldrel
 - release
 - devel

# We need to install BiocInstaller for testing Bioconductor packages
bioc_required: true

# Only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
